import type { Article } from "@/types";

export const MOCK_ARTICLES: Article[] = [
  {
    id: "1",
    title: "OpenAI Unveils GPT-5: A Leap Forward in Multimodal Intelligence",
    content: `OpenAI has announced the release of GPT-5, its most advanced language model to date. The new model demonstrates unprecedented capabilities in reasoning, code generation, and multimodal understanding, processing text, images, and audio seamlessly.\n\nIn benchmark tests, GPT-5 scored 92% on the MMLU professional knowledge test — a 15-point improvement over its predecessor. Developers are already reporting 40% productivity gains in complex coding tasks, with the model able to debug multi-file codebases and suggest architectural improvements.\n\nThe release comes amid fierce competition with Google's Gemini Ultra and Anthropic's Claude 4, signaling a new phase in the AI race where raw capability is being matched with careful safety engineering. OpenAI has partnered with major hospitals and financial institutions to pilot the model under supervised conditions.`,
    category: "Technology",
    imageUrl: "https://picsum.photos/seed/tech1/800/450",
    author: "Sarah Chen",
    publishedAt: "2026-04-20T08:30:00Z",
    likeCount: 1842,
    tags: ["AI", "OpenAI", "GPT-5", "Machine Learning"],
  },
  {
    id: "2",
    title: "Federal Reserve Signals Rate Cuts Amid Cooling Inflation Data",
    content: `The Federal Reserve has hinted at potential interest rate cuts in the coming quarter after inflation dropped to 2.3%, its lowest level since 2021. Fed Chair Jerome Powell said the central bank is "cautiously optimistic" but will wait for more data before acting.\n\nMarkets rallied sharply on the news, with the S&P 500 gaining 2.1% and the Nasdaq surging 3.4%. Mortgage rates, which peaked at 7.8% last year, could fall to 6.2% by year's end if the Fed proceeds with three anticipated cuts.\n\nEconomists are divided on the timeline. Some argue that labor market tightness — with unemployment at 3.8% — gives the Fed room to wait, while others warn that delaying cuts risks tipping the economy into a soft landing that could quickly become a hard one.`,
    category: "Business",
    imageUrl: "https://picsum.photos/seed/biz1/800/450",
    author: "Marcus Rivera",
    publishedAt: "2026-04-19T14:15:00Z",
    likeCount: 934,
    tags: ["Federal Reserve", "Interest Rates", "Economy", "Inflation"],
  },
  {
    id: "3",
    title: "New Study Links Gut Microbiome Diversity to Reduced Cancer Risk",
    content: `A landmark study published in Nature Medicine involving 85,000 participants across 12 countries has found a strong correlation between gut microbiome diversity and a 34% reduced risk of colorectal cancer. The research tracked subjects over 15 years and used advanced metagenomic sequencing.\n\nResearchers identified 47 specific bacterial species associated with protective effects, most of which thrive on high-fiber, plant-rich diets. The findings suggest that relatively simple dietary interventions could have measurable cancer-prevention benefits within 6-12 months.\n\nDr. Amara Osei of the University of Ghana, one of the study's lead authors, said this research opens the door to microbiome-based therapies: "We're not just talking about yogurt and probiotics — we're talking about precision nutrition as medicine." Clinical trials for targeted probiotic therapies are already underway.`,
    category: "Health",
    imageUrl: "https://picsum.photos/seed/health1/800/450",
    author: "Dr. Priya Nair",
    publishedAt: "2026-04-18T10:00:00Z",
    likeCount: 2103,
    tags: ["Cancer Research", "Gut Health", "Microbiome", "Nutrition"],
  },
  {
    id: "4",
    title:
      "James Webb Space Telescope Detects Water Vapor on Potentially Habitable Exoplanet",
    content: `NASA's James Webb Space Telescope has detected water vapor in the atmosphere of K2-18b, an exoplanet 120 light-years away that sits in the habitable zone of its host star. The discovery is considered one of the most significant in the search for extraterrestrial life.\n\nThe telescope's infrared spectrometer also detected carbon dioxide and methane — a combination that some scientists say could indicate biological activity, though definitive conclusions remain years away. K2-18b is 2.6 times Earth's radius, classifying it as a "Hycean world" — possibly covered by a vast, warm ocean beneath a hydrogen-rich atmosphere.\n\nDr. Nikku Madhusudhan of Cambridge University, who led the analysis, described it as "a watershed moment in the history of astronomy." Teams are now preparing follow-up observations to search for dimethyl sulfide, a compound produced almost exclusively by living organisms on Earth.`,
    category: "Science",
    imageUrl: "https://picsum.photos/seed/sci1/800/450",
    author: "Elena Vasquez",
    publishedAt: "2026-04-17T16:45:00Z",
    likeCount: 3211,
    tags: ["NASA", "Exoplanet", "Space", "Astrobiology", "JWST"],
  },
  {
    id: "5",
    title:
      "Manchester City Clinch Champions League Title in Historic 6-1 Victory",
    content: `Manchester City claimed their third consecutive UEFA Champions League title with a stunning 6-1 victory over Paris Saint-Germain at Wembley Stadium. Erling Haaland scored four goals and provided two assists in what pundits are calling the greatest individual Champions League final performance ever.\n\nPep Guardiola's side dominated from the opening whistle, with City's high press forcing 23 turnovers in the attacking third. The scoreline flattered PSG, who were reduced to nine men by the 60th minute. City's fourth goal — a 45-meter solo run by Phil Foden — has already been viewed 80 million times online.\n\n"This is the greatest team I've ever managed," Guardiola said at the post-match press conference. City now join Real Madrid as the only clubs to win three consecutive Champions League titles in the modern era. The celebrations in Manchester are expected to draw over 500,000 fans to the trophy parade.`,
    category: "Sports",
    imageUrl: "https://picsum.photos/seed/sport1/800/450",
    author: "Jamie Thompson",
    publishedAt: "2026-04-16T22:00:00Z",
    likeCount: 4567,
    tags: ["Champions League", "Manchester City", "Football", "Haaland"],
  },
  {
    id: "6",
    title:
      "Netflix's 'Parallax' Breaks Streaming Records with 200M Views in First Week",
    content: `Netflix's science fiction epic 'Parallax' has shattered global streaming records, accumulating 200 million views in its first week — surpassing even Squid Game's inaugural numbers. The show, set in a near-future where memories can be legally traded, has sparked fierce discussion about identity and consciousness.\n\nDirected by Chloe Zhao and starring Lupita Nyong'o and Dev Patel, the series was produced with an unprecedented $180 million budget. Critics have lauded its visual language — shot entirely on location across Iceland, Japan, and the Atacama Desert — and its screenplay, which took four writers six years to develop.\n\nThe cultural impact extends beyond viewership: philosophy professors are assigning episodes as course material, and several countries have begun debating legislation around memory privacy. Netflix has already greenlit two more seasons and a companion documentary series.`,
    category: "Entertainment",
    imageUrl: "https://picsum.photos/seed/ent1/800/450",
    author: "Kenji Watanabe",
    publishedAt: "2026-04-15T09:30:00Z",
    likeCount: 5890,
    tags: ["Netflix", "Streaming", "Science Fiction", "Chloe Zhao"],
  },
  {
    id: "7",
    title:
      "EU Parliament Passes Landmark AI Governance Act with Strict Liability Rules",
    content: `The European Parliament has approved the AI Governance Act by a 612-83 vote, establishing the world's strictest liability framework for artificial intelligence systems. The law assigns legal personhood to certain high-risk AI systems and requires companies to maintain comprehensive audit trails.\n\nCompanies deploying general-purpose AI in healthcare, financial services, or public infrastructure face fines of up to 6% of global revenue for violations — stricter than GDPR penalties. The law also mandates explainability: AI systems must be able to provide human-readable justifications for any consequential decision.\n\nTech industry groups have warned of a "regulatory chill" that could drive AI development to less regulated markets, while civil liberties organizations have praised the legislation as a global model. The US, UK, and Japan are all studying the framework as a potential template for their own AI regulation efforts.`,
    category: "Politics",
    imageUrl: "https://picsum.photos/seed/pol1/800/450",
    author: "Anna Kowalski",
    publishedAt: "2026-04-14T11:00:00Z",
    likeCount: 1203,
    tags: ["AI Regulation", "EU", "Technology Law", "Governance"],
  },
  {
    id: "8",
    title:
      "Apple Vision Pro 3 Introduces Neural Interface for Hands-Free Control",
    content: `Apple has unveiled the Vision Pro 3, featuring a neural interface band worn on the wrist that allows users to control the device through thought alone. The EEG-based system, developed over five years, achieves 94% accuracy for gesture prediction without physical movement.\n\nThe headset weighs 180 grams — half the original model — and lasts 8 hours on battery. Apple is pitching the device to enterprise users, with partnerships already signed with Boeing for aircraft maintenance visualization and Johns Hopkins for surgical planning applications.\n\nAt $3,499, it remains a premium product, but Apple's move-down strategy is evident: a $1,799 "Air" variant without the neural band is launching simultaneously. Analysts predict Apple will ship 4 million units in the first fiscal year, up from 500,000 for the original Vision Pro.`,
    category: "Technology",
    imageUrl: "https://picsum.photos/seed/tech2/800/450",
    author: "Lisa Park",
    publishedAt: "2026-04-13T13:00:00Z",
    likeCount: 2876,
    tags: ["Apple", "AR/VR", "Neural Interface", "Wearables"],
  },
  {
    id: "9",
    title:
      "CRISPR Gene Therapy Shows 98% Success Rate in Sickle Cell Disease Trial",
    content: `A Phase 3 clinical trial of a CRISPR-based gene therapy for sickle cell disease has achieved a 98% success rate across 210 patients, effectively curing the debilitating condition in all but four cases. The treatment, developed jointly by Vertex Pharmaceuticals and the Broad Institute, edits a single nucleotide in the HBB gene.\n\nPatients who received the therapy have now been pain-crisis-free for an average of 28 months. One patient, 19-year-old Marcus Johnson from Atlanta, described his experience: "I've been hospitalized 12 times in the last four years. Since the treatment, I've run a 5K and started college." The FDA has placed the therapy on a priority review track.\n\nThe treatment currently costs $2.2 million per patient, raising access equity concerns. However, the manufacturers have committed to tiered pricing for low-income countries and are working with the Gates Foundation on a manufacturing scale-up plan.`,
    category: "Health",
    imageUrl: "https://picsum.photos/seed/health2/800/450",
    author: "Dr. James Okonkwo",
    publishedAt: "2026-04-12T08:45:00Z",
    likeCount: 3405,
    tags: ["CRISPR", "Gene Therapy", "Sickle Cell", "Biotech"],
  },
  {
    id: "10",
    title:
      "China's Quantum Computer Solves 100-Year-Old Math Problem in 47 Minutes",
    content: `Chinese researchers at the University of Science and Technology of China (USTC) have used their 1000-qubit quantum processor, "Jiuzhang 4.0," to solve a classical combinatorial optimization problem that would take the world's fastest supercomputer an estimated 100 years. The result, published in Nature, is considered the strongest demonstration of "quantum advantage" to date.\n\nThe problem — a variant of the traveling salesman problem with 500 nodes — has direct applications in logistics, drug discovery, and financial portfolio optimization. Several logistics companies have already expressed interest in early access.\n\nExperts caution that error rates remain a significant challenge. The computation required 47 minutes and numerous corrections, while a fully fault-tolerant version would achieve the same result in seconds. Nevertheless, IBM's quantum research head, Dr. Sergio Boixo, called the result "a major milestone that we cannot dismiss."`,
    category: "Science",
    imageUrl: "https://picsum.photos/seed/sci2/800/450",
    author: "Wei Zhang",
    publishedAt: "2026-04-11T15:30:00Z",
    likeCount: 2198,
    tags: ["Quantum Computing", "China", "USTC", "Physics"],
  },
  {
    id: "11",
    title: "Simone Biles Announces Return for 2028 Olympics at Age 31",
    content: `Legendary gymnast Simone Biles has announced she will compete at the 2028 Los Angeles Olympics, aiming to become the first gymnast to win medals at four consecutive Games. Biles, who will be 31 at the time, says she has been training a new vault that has never been attempted in competition.\n\n"People keep asking me when I'll stop," Biles said at a press conference in Houston. "The answer is when it stops being fun. Right now, every morning I wake up excited to train." Her coach Laurent Landi confirmed she is in the best physical shape of her career, aided by personalized biomechanical AI coaching tools developed with MIT.\n\nBiles currently holds the record for most World Championship medals (30) and is widely considered the greatest gymnast of all time. Her participation is expected to be the defining narrative of the 2028 Games, which LA is projecting to draw 3.2 billion viewers globally.`,
    category: "Sports",
    imageUrl: "https://picsum.photos/seed/sport2/800/450",
    author: "Maria Santos",
    publishedAt: "2026-04-10T10:15:00Z",
    likeCount: 6102,
    tags: ["Olympics", "Gymnastics", "Simone Biles", "LA 2028"],
  },
  {
    id: "12",
    title: "Universal Music Group Acquires AI Startup for $4.2 Billion",
    content: `Universal Music Group has acquired SoundMind, an AI music creation startup, for $4.2 billion — the largest acquisition in the music industry's history. SoundMind's technology can generate studio-quality music in any genre, style, or emotional tone within seconds, trained on a library of 50 million licensed tracks.\n\nThe deal signals a fundamental shift in how the industry views AI: rather than fighting it, major labels are now racing to own it. UMG plans to integrate SoundMind's technology into its production pipeline and offer it as a subscription service to independent artists by Q4 2026.\n\nMusicians' unions have reacted with alarm. The American Federation of Musicians has called for Congressional hearings, arguing the acquisition threatens 200,000 session musician jobs. UMG CEO Lucian Grainge countered that the technology will "expand the creative universe rather than replace human artistry," pledging a $500 million fund to support human musicians.`,
    category: "Entertainment",
    imageUrl: "https://picsum.photos/seed/ent2/800/450",
    author: "Tyler Brooks",
    publishedAt: "2026-04-09T12:00:00Z",
    likeCount: 1567,
    tags: ["Music Industry", "AI", "UMG", "Acquisition"],
  },
  {
    id: "13",
    title: "G20 Summit Reaches Historic Climate Deal: Net-Zero by 2045",
    content: `Leaders of the G20 nations have signed the Geneva Climate Accord, committing to reach net-zero carbon emissions by 2045 — five years ahead of previous targets. The deal includes $2.5 trillion in annual climate finance for developing nations and a shared carbon pricing mechanism.\n\nThe agreement was brokered after 72 hours of negotiations, with China and India making unexpected concessions in exchange for technology transfer guarantees. The deal mandates that coal power must be phased out in G20 nations by 2035, with a $400 billion just-transition fund to support affected workers and communities.\n\nClimate scientists have called the accord "the most significant climate action since the Paris Agreement," though some argue the 2045 target is still insufficient to limit warming to 1.5°C. Implementation will be tracked by a new independent body with authority to impose trade tariffs on non-compliant nations.`,
    category: "Politics",
    imageUrl: "https://picsum.photos/seed/pol2/800/450",
    author: "Sophie Laurent",
    publishedAt: "2026-04-08T17:00:00Z",
    likeCount: 2890,
    tags: ["Climate Change", "G20", "Net Zero", "International Policy"],
  },
  {
    id: "14",
    title:
      "Tesla's Robotaxi Fleet Surpasses 1 Billion Miles Without Human Intervention",
    content: `Tesla has announced that its autonomous robotaxi fleet has completed 1 billion fully driverless miles across 12 US cities — a milestone that CEO Elon Musk called "the beginning of the end of human driving." The fleet of 50,000 Model 3 and Cybercab vehicles has maintained a safety record 6x better than the human average.\n\nThe company's Full Self-Driving system, now on version 14.2, uses a purely vision-based approach without LiDAR — a controversial decision that has been validated by the safety data. Tesla plans to expand to 50 cities by year's end and has filed for operating permits in the EU, UK, and Australia.\n\nCompetitors Waymo and Cruise are watching closely. Waymo, which uses LiDAR and has operated for longer, has reached only 50 million supervised miles. The diverging data is reigniting the LiDAR vs. cameras debate that has divided the autonomous vehicle industry for a decade.`,
    category: "Technology",
    imageUrl: "https://picsum.photos/seed/tech3/800/450",
    author: "Alex Morgan",
    publishedAt: "2026-04-07T09:00:00Z",
    likeCount: 3241,
    tags: ["Tesla", "Autonomous Vehicles", "Self-Driving", "EVs"],
  },
  {
    id: "15",
    title: "New Alzheimer's Drug Halts Disease Progression in 73% of Patients",
    content: `A new drug called Remibrutinib has demonstrated the ability to halt Alzheimer's disease progression in 73% of early-stage patients over a 24-month trial period. The drug works by targeting a previously overlooked pathway involving microglial activation — the brain's immune cells.\n\nUnlike earlier Alzheimer's treatments that focused solely on amyloid plaques, Remibrutinib addresses neuroinflammation as a co-driver of the disease. Patients in the trial showed stable cognitive scores and, in 31% of cases, measurable improvement. The drug is taken as a daily oral capsule, making it far more accessible than IV-administered alternatives.\n\nThe FDA has granted Breakthrough Therapy designation, putting it on track for approval within 18 months. If approved, it would be the most effective Alzheimer's treatment ever developed. An estimated 55 million people worldwide live with dementia, and Alzheimer's accounts for 60-70% of cases.`,
    category: "Health",
    imageUrl: "https://picsum.photos/seed/health3/800/450",
    author: "Dr. Emily Hart",
    publishedAt: "2026-04-06T11:30:00Z",
    likeCount: 4123,
    tags: ["Alzheimer's", "Neuroscience", "Drug Trial", "FDA"],
  },
  {
    id: "16",
    title: "First Nuclear Fusion Plant Begins Commercial Power Generation",
    content: `Commonwealth Fusion Systems (CFS) has officially flipped the switch on SPARC-1, the world's first commercial nuclear fusion power plant, feeding electricity into the Massachusetts grid. The milestone was 70 years in the making and follows CFS's 2022 breakthrough with high-temperature superconducting magnets.\n\nSPARC-1 currently generates 400 megawatts — enough to power about 300,000 homes — with plans to scale to 1 gigawatt within three years. The plant's fuel cycle uses deuterium and tritium, both abundant, and produces no long-lived radioactive waste, addressing two of nuclear fission's major concerns.\n\nThe Biden administration has committed $12 billion to accelerate 20 additional fusion plants by 2035. Energy analysts predict fusion could represent 15% of global electricity generation by 2050. "We solved fusion," CFS CEO Bob Mumgaard said. "Now we have to industrialize it."`,
    category: "Science",
    imageUrl: "https://picsum.photos/seed/sci3/800/450",
    author: "Daniel Kim",
    publishedAt: "2026-04-05T14:00:00Z",
    likeCount: 5643,
    tags: ["Nuclear Fusion", "Clean Energy", "CFS", "SPARC"],
  },
  {
    id: "17",
    title:
      "LeBron James Retires After 23 NBA Seasons with 45,000 Career Points",
    content: `LeBron James has officially announced his retirement from professional basketball at age 41, ending a 23-season career in which he shattered virtually every significant offensive record in NBA history. James finished with 45,192 career points, 11,423 assists, and 10,987 rebounds — a statistical combination no player has ever approached.\n\n"I played because I loved the game, and I love it just as much today as I did when I was 18," James said at a press conference in Los Angeles. "But I want to be present for my kids, and the time is right." His final game, a 38-point performance in a playoff loss to Oklahoma City Thunder, was watched by 24 million viewers.\n\nJames leaves behind a complex legacy: four championships with three different franchises, two Olympic gold medals, and an off-court business empire valued at $1.2 billion. His foundation has funded college education for over 3,000 students through the I PROMISE School. Commissioner Adam Silver called him "the most complete player the game has ever seen."`,
    category: "Sports",
    imageUrl: "https://picsum.photos/seed/sport3/800/450",
    author: "Chris Williams",
    publishedAt: "2026-04-04T20:00:00Z",
    likeCount: 8932,
    tags: ["NBA", "LeBron James", "Basketball", "Retirement"],
  },
  {
    id: "18",
    title:
      "Cannes 2026: Korean Director Bong Joon-ho Wins Palme d'Or for Second Time",
    content: `Bong Joon-ho's film "Meridian" has won the Palme d'Or at the 2026 Cannes Film Festival, making him only the fourth director in history to win the award twice. The film, a three-hour meditation on memory and national identity set across three generations of a Korean family, received a 12-minute standing ovation at its premiere.\n\nThe jury, presided over by Cate Blanchett, praised "Meridian" for its "extraordinary visual language and emotional depth that transcends cultural boundaries." The film features no dialogue for its final 40 minutes, relying entirely on performance and cinematography to deliver its conclusion.\n\nJury Prize went to French director Claire Denis for "Solstice," while Best Actress was awarded to Zendaya for her role as a mute underwater archaeologist in British thriller "The Depth." The festival drew 180,000 attendees and accredited 4,500 journalists — a new record.`,
    category: "Entertainment",
    imageUrl: "https://picsum.photos/seed/ent3/800/450",
    author: "Isabella Romano",
    publishedAt: "2026-04-03T16:30:00Z",
    likeCount: 2341,
    tags: ["Cannes", "Film", "Bong Joon-ho", "Palme d'Or"],
  },
  {
    id: "19",
    title:
      "India Becomes World's Largest Economy, Surpassing the United States",
    content: `India has officially overtaken the United States to become the world's largest economy by nominal GDP, reaching $30.1 trillion to the US's $29.8 trillion, according to updated World Bank figures. The milestone, anticipated by economists since 2022, reflects India's 8.2% annual growth rate sustained over a decade.\n\nPrime Minister Modi called it "the fulfillment of our civilizational destiny" at a ceremony in New Delhi attended by 50 world leaders. India's growth has been driven by a young demographic dividend — 65% of the population is under 35 — its dominance in software and digital services, and massive infrastructure investment including 45,000 km of new highways built since 2020.\n\nThe geopolitical implications are profound. India is expected to host the next G7 summit and will have significant influence over global trade, climate, and technology governance. However, analysts note that per-capita income remains $21,000, compared to $81,000 in the US, meaning the wealth distribution challenge is enormous.`,
    category: "Business",
    imageUrl: "https://picsum.photos/seed/biz2/800/450",
    author: "Rohit Sharma",
    publishedAt: "2026-04-02T08:00:00Z",
    likeCount: 4521,
    tags: ["India", "Economy", "GDP", "Global Markets"],
  },
  {
    id: "20",
    title:
      "UN Summit on Digital Rights Adopts Universal Internet Access Charter",
    content: `The United Nations has adopted the Universal Internet Access Charter, signed by 142 countries, establishing internet access as a fundamental human right and committing to achieve universal connectivity by 2030. The charter mandates affordable broadband for all citizens and prohibits governments from arbitrarily disconnecting populations.\n\nThe agreement includes a $350 billion fund, partly financed by a proposed 0.1% digital services tax on tech company revenues above $1 billion. SpaceX's Starlink constellation and Amazon's Project Kuiper are expected to play key roles in reaching remote and rural populations.\n\nCritics note that key authoritarian nations, including Russia and North Korea, refused to sign. China signed with an abstention on the free-speech provisions. Advocates argue the charter's value lies less in immediate enforcement and more in establishing a global norm that can be used to hold governments accountable through diplomatic and trade mechanisms.`,
    category: "Politics",
    imageUrl: "https://picsum.photos/seed/pol3/800/450",
    author: "Fatima Al-Rashid",
    publishedAt: "2026-04-01T10:00:00Z",
    likeCount: 1876,
    tags: ["UN", "Digital Rights", "Internet Access", "Human Rights"],
  },
];
