/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlgorithmSource = { 'hybrid' : null } |
  { 'collaborative' : null } |
  { 'contentBased' : null };
export interface Article {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'category' : string,
  'termFrequencies' : Array<[string, number]>,
}
export type ArticleId = bigint;
export type InteractionType = { 'like' : null } |
  { 'click' : null };
export interface RecommendationResult {
  'algorithmSource' : AlgorithmSource,
  'article' : Article,
  'score' : number,
  'confidence' : number,
}
export interface RecommendationsResponse {
  'algorithmUsed' : AlgorithmSource,
  'recommendations' : Array<RecommendationResult>,
}
export interface RecordInteractionRequest {
  'interactionType' : InteractionType,
  'userId' : UserId,
  'articleId' : ArticleId,
}
export interface SearchEntry { 'searchTerm' : string, 'timestamp' : Timestamp }
export interface SubmitArticleRequest {
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'category' : string,
}
export type SubmitArticleResult = { 'failure' : { 'reason' : string } } |
  { 'success' : { 'articleId' : ArticleId } };
export interface SystemMetrics {
  'averageSimilarityScore' : number,
  'totalArticles' : bigint,
  'totalUsers' : bigint,
  'totalInteractions' : bigint,
  'recommendationCoverage' : number,
}
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'region' : [] | [string],
  'displayName' : [] | [string],
  'preferredCategories' : [] | [Array<string>],
  'interests' : [] | [Array<string>],
}
export type UserId = string;
export interface UserProfile {
  'region' : string,
  'readingHistory' : Array<ArticleId>,
  'displayName' : string,
  'preferredCategories' : Array<string>,
  'interests' : Array<string>,
  'createdAt' : Timestamp,
  'principalText' : string,
}
export interface _SERVICE {
  'getArticleDetail' : ActorMethod<[ArticleId], [] | [Article]>,
  'getArticleLikeCount' : ActorMethod<[ArticleId], bigint>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getMetrics' : ActorMethod<[], SystemMetrics>,
  'getRecommendations' : ActorMethod<
    [UserId, AlgorithmSource, [] | [ArticleId], bigint],
    RecommendationsResponse
  >,
  'getSearchHistory' : ActorMethod<[], Array<SearchEntry>>,
  'getTrendingArticles' : ActorMethod<[[] | [bigint]], Array<Article>>,
  'getUserLikes' : ActorMethod<[], Array<ArticleId>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'recordInteraction' : ActorMethod<[RecordInteractionRequest], undefined>,
  'recordProfileInteraction' : ActorMethod<[ArticleId], undefined>,
  'searchArticles' : ActorMethod<[string, [] | [string]], Array<Article>>,
  'submitArticle' : ActorMethod<[SubmitArticleRequest], SubmitArticleResult>,
  'toggleArticleLike' : ActorMethod<[ArticleId], bigint>,
  'updateUserProfile' : ActorMethod<[UpdateProfileRequest], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];