/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArticleId = IDL.Nat;
export const Article = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : IDL.Text,
  'termFrequencies' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const SystemMetrics = IDL.Record({
  'averageSimilarityScore' : IDL.Float64,
  'totalArticles' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalInteractions' : IDL.Nat,
  'recommendationCoverage' : IDL.Float64,
});
export const UserId = IDL.Text;
export const AlgorithmSource = IDL.Variant({
  'hybrid' : IDL.Null,
  'collaborative' : IDL.Null,
  'contentBased' : IDL.Null,
});
export const RecommendationResult = IDL.Record({
  'algorithmSource' : AlgorithmSource,
  'article' : Article,
  'score' : IDL.Float64,
  'confidence' : IDL.Float64,
});
export const RecommendationsResponse = IDL.Record({
  'algorithmUsed' : AlgorithmSource,
  'recommendations' : IDL.Vec(RecommendationResult),
});
export const Timestamp = IDL.Int;
export const SearchEntry = IDL.Record({
  'searchTerm' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserProfile = IDL.Record({
  'region' : IDL.Text,
  'readingHistory' : IDL.Vec(ArticleId),
  'displayName' : IDL.Text,
  'preferredCategories' : IDL.Vec(IDL.Text),
  'interests' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'principalText' : IDL.Text,
});
export const InteractionType = IDL.Variant({
  'like' : IDL.Null,
  'click' : IDL.Null,
});
export const RecordInteractionRequest = IDL.Record({
  'interactionType' : InteractionType,
  'userId' : UserId,
  'articleId' : ArticleId,
});
export const SubmitArticleRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const SubmitArticleResult = IDL.Variant({
  'failure' : IDL.Record({ 'reason' : IDL.Text }),
  'success' : IDL.Record({ 'articleId' : ArticleId }),
});
export const UpdateProfileRequest = IDL.Record({
  'region' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'preferredCategories' : IDL.Opt(IDL.Vec(IDL.Text)),
  'interests' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  'getArticleDetail' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getArticleLikeCount' : IDL.Func([ArticleId], [IDL.Nat], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'getRecommendations' : IDL.Func(
      [UserId, AlgorithmSource, IDL.Opt(ArticleId), IDL.Nat],
      [RecommendationsResponse],
      ['query'],
    ),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchEntry)], ['query']),
  'getTrendingArticles' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getUserLikes' : IDL.Func([], [IDL.Vec(ArticleId)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], []),
  'recordInteraction' : IDL.Func([RecordInteractionRequest], [], []),
  'recordProfileInteraction' : IDL.Func([ArticleId], [], []),
  'searchArticles' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Article)],
      [],
    ),
  'submitArticle' : IDL.Func([SubmitArticleRequest], [SubmitArticleResult], []),
  'toggleArticleLike' : IDL.Func([ArticleId], [IDL.Nat], []),
  'updateUserProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArticleId = IDL.Nat;
  const Article = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : IDL.Text,
    'termFrequencies' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const SystemMetrics = IDL.Record({
    'averageSimilarityScore' : IDL.Float64,
    'totalArticles' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalInteractions' : IDL.Nat,
    'recommendationCoverage' : IDL.Float64,
  });
  const UserId = IDL.Text;
  const AlgorithmSource = IDL.Variant({
    'hybrid' : IDL.Null,
    'collaborative' : IDL.Null,
    'contentBased' : IDL.Null,
  });
  const RecommendationResult = IDL.Record({
    'algorithmSource' : AlgorithmSource,
    'article' : Article,
    'score' : IDL.Float64,
    'confidence' : IDL.Float64,
  });
  const RecommendationsResponse = IDL.Record({
    'algorithmUsed' : AlgorithmSource,
    'recommendations' : IDL.Vec(RecommendationResult),
  });
  const Timestamp = IDL.Int;
  const SearchEntry = IDL.Record({
    'searchTerm' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserProfile = IDL.Record({
    'region' : IDL.Text,
    'readingHistory' : IDL.Vec(ArticleId),
    'displayName' : IDL.Text,
    'preferredCategories' : IDL.Vec(IDL.Text),
    'interests' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'principalText' : IDL.Text,
  });
  const InteractionType = IDL.Variant({
    'like' : IDL.Null,
    'click' : IDL.Null,
  });
  const RecordInteractionRequest = IDL.Record({
    'interactionType' : InteractionType,
    'userId' : UserId,
    'articleId' : ArticleId,
  });
  const SubmitArticleRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const SubmitArticleResult = IDL.Variant({
    'failure' : IDL.Record({ 'reason' : IDL.Text }),
    'success' : IDL.Record({ 'articleId' : ArticleId }),
  });
  const UpdateProfileRequest = IDL.Record({
    'region' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'preferredCategories' : IDL.Opt(IDL.Vec(IDL.Text)),
    'interests' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    'getArticleDetail' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getArticleLikeCount' : IDL.Func([ArticleId], [IDL.Nat], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'getRecommendations' : IDL.Func(
        [UserId, AlgorithmSource, IDL.Opt(ArticleId), IDL.Nat],
        [RecommendationsResponse],
        ['query'],
      ),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchEntry)], ['query']),
    'getTrendingArticles' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getUserLikes' : IDL.Func([], [IDL.Vec(ArticleId)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], []),
    'recordInteraction' : IDL.Func([RecordInteractionRequest], [], []),
    'recordProfileInteraction' : IDL.Func([ArticleId], [], []),
    'searchArticles' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Article)],
        [],
      ),
    'submitArticle' : IDL.Func(
        [SubmitArticleRequest],
        [SubmitArticleResult],
        [],
      ),
    'toggleArticleLike' : IDL.Func([ArticleId], [IDL.Nat], []),
    'updateUserProfile' : IDL.Func([UpdateProfileRequest], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };