/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SystemMetrics {
    averageSimilarityScore: number;
    totalArticles: bigint;
    totalUsers: bigint;
    totalInteractions: bigint;
    recommendationCoverage: number;
}
export interface SubmitArticleRequest {
    title: string;
    content: string;
    tags: Array<string>;
    category: string;
}
export type Timestamp = bigint;
export type SubmitArticleResult = {
    __kind__: "failure";
    failure: {
        reason: string;
    };
} | {
    __kind__: "success";
    success: {
        articleId: ArticleId;
    };
};
export interface RecordInteractionRequest {
    interactionType: InteractionType;
    userId: UserId;
    articleId: ArticleId;
}
export type ArticleId = bigint;
export interface RecommendationResult {
    algorithmSource: AlgorithmSource;
    article: Article;
    score: number;
    confidence: number;
}
export type UserId = string;
export interface UpdateProfileRequest {
    region?: string;
    displayName?: string;
    preferredCategories?: Array<string>;
    interests?: Array<string>;
}
export interface RecommendationsResponse {
    algorithmUsed: AlgorithmSource;
    recommendations: Array<RecommendationResult>;
}
export interface SearchEntry {
    searchTerm: string;
    timestamp: Timestamp;
}
export interface Article {
    id: ArticleId;
    title: string;
    content: string;
    category: string;
    termFrequencies: Array<[string, number]>;
}
export interface UserProfile {
    region: string;
    readingHistory: Array<ArticleId>;
    displayName: string;
    preferredCategories: Array<string>;
    interests: Array<string>;
    createdAt: Timestamp;
    principalText: string;
}
export enum AlgorithmSource {
    hybrid = "hybrid",
    collaborative = "collaborative",
    contentBased = "contentBased"
}
export enum InteractionType {
    like = "like",
    click = "click"
}
export interface backendInterface {
    getArticleDetail(articleId: ArticleId): Promise<Article | null>;
    getArticleLikeCount(articleId: ArticleId): Promise<bigint>;
    getArticles(): Promise<Array<Article>>;
    getMetrics(): Promise<SystemMetrics>;
    getRecommendations(userId: UserId, algorithm: AlgorithmSource, seedArticleId: ArticleId | null, topN: bigint): Promise<RecommendationsResponse>;
    getSearchHistory(): Promise<Array<SearchEntry>>;
    getTrendingArticles(limit: bigint | null): Promise<Array<Article>>;
    getUserLikes(): Promise<Array<ArticleId>>;
    getUserProfile(): Promise<UserProfile>;
    recordInteraction(req: RecordInteractionRequest): Promise<void>;
    recordProfileInteraction(articleId: ArticleId): Promise<void>;
    searchArticles(searchQuery: string, category: string | null): Promise<Array<Article>>;
    submitArticle(req: SubmitArticleRequest): Promise<SubmitArticleResult>;
    toggleArticleLike(articleId: ArticleId): Promise<bigint>;
    updateUserProfile(req: UpdateProfileRequest): Promise<UserProfile>;
}
import type { AlgorithmSource as _AlgorithmSource, Article as _Article, ArticleId as _ArticleId, InteractionType as _InteractionType, RecommendationResult as _RecommendationResult, RecommendationsResponse as _RecommendationsResponse, RecordInteractionRequest as _RecordInteractionRequest, SubmitArticleResult as _SubmitArticleResult, UpdateProfileRequest as _UpdateProfileRequest, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getArticleDetail(arg0: ArticleId): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleDetail(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleDetail(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleLikeCount(arg0: ArticleId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleLikeCount(arg0);
            return result;
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return result;
        }
    }
    async getMetrics(): Promise<SystemMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getRecommendations(arg0: UserId, arg1: AlgorithmSource, arg2: ArticleId | null, arg3: bigint): Promise<RecommendationsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(arg0, to_candid_AlgorithmSource_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_RecommendationsResponse_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(arg0, to_candid_AlgorithmSource_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_RecommendationsResponse_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSearchHistory(): Promise<Array<SearchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchHistory();
            return result;
        }
    }
    async getTrendingArticles(arg0: bigint | null): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingArticles(to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingArticles(to_candid_opt_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserLikes(): Promise<Array<ArticleId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLikes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLikes();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return result;
        }
    }
    async recordInteraction(arg0: RecordInteractionRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordInteraction(to_candid_RecordInteractionRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordInteraction(to_candid_RecordInteractionRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordProfileInteraction(arg0: ArticleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProfileInteraction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProfileInteraction(arg0);
            return result;
        }
    }
    async searchArticles(arg0: string, arg1: string | null): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitArticle(arg0: SubmitArticleRequest): Promise<SubmitArticleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitArticle(arg0);
                return from_candid_SubmitArticleResult_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitArticle(arg0);
            return from_candid_SubmitArticleResult_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleArticleLike(arg0: ArticleId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleArticleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleArticleLike(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: UpdateProfileRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UpdateProfileRequest_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UpdateProfileRequest_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AlgorithmSource_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlgorithmSource): AlgorithmSource {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationResult): RecommendationResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationsResponse_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationsResponse): RecommendationsResponse {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitArticleResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitArticleResult): SubmitArticleResult {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    algorithmSource: _AlgorithmSource;
    article: _Article;
    score: number;
    confidence: number;
}): {
    algorithmSource: AlgorithmSource;
    article: Article;
    score: number;
    confidence: number;
} {
    return {
        algorithmSource: from_candid_AlgorithmSource_n7(_uploadFile, _downloadFile, value.algorithmSource),
        article: value.article,
        score: value.score,
        confidence: value.confidence
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    algorithmUsed: _AlgorithmSource;
    recommendations: Array<_RecommendationResult>;
}): {
    algorithmUsed: AlgorithmSource;
    recommendations: Array<RecommendationResult>;
} {
    return {
        algorithmUsed: from_candid_AlgorithmSource_n7(_uploadFile, _downloadFile, value.algorithmUsed),
        recommendations: from_candid_vec_n9(_uploadFile, _downloadFile, value.recommendations)
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failure: {
        reason: string;
    };
} | {
    success: {
        articleId: _ArticleId;
    };
}): {
    __kind__: "failure";
    failure: {
        reason: string;
    };
} | {
    __kind__: "success";
    success: {
        articleId: ArticleId;
    };
} {
    return "failure" in value ? {
        __kind__: "failure",
        failure: value.failure
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hybrid: null;
} | {
    collaborative: null;
} | {
    contentBased: null;
}): AlgorithmSource {
    return "hybrid" in value ? AlgorithmSource.hybrid : "collaborative" in value ? AlgorithmSource.collaborative : "contentBased" in value ? AlgorithmSource.contentBased : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecommendationResult>): Array<RecommendationResult> {
    return value.map((x)=>from_candid_RecommendationResult_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AlgorithmSource_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlgorithmSource): _AlgorithmSource {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_InteractionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): _InteractionType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_RecordInteractionRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordInteractionRequest): _RecordInteractionRequest {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleId | null): [] | [_ArticleId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interactionType: InteractionType;
    userId: UserId;
    articleId: ArticleId;
}): {
    interactionType: _InteractionType;
    userId: _UserId;
    articleId: _ArticleId;
} {
    return {
        interactionType: to_candid_InteractionType_n15(_uploadFile, _downloadFile, value.interactionType),
        userId: value.userId,
        articleId: value.articleId
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region?: string;
    displayName?: string;
    preferredCategories?: Array<string>;
    interests?: Array<string>;
}): {
    region: [] | [string];
    displayName: [] | [string];
    preferredCategories: [] | [Array<string>];
    interests: [] | [Array<string>];
} {
    return {
        region: value.region ? candid_some(value.region) : candid_none(),
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        preferredCategories: value.preferredCategories ? candid_some(value.preferredCategories) : candid_none(),
        interests: value.interests ? candid_some(value.interests) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InteractionType): {
    like: null;
} | {
    click: null;
} {
    return value == InteractionType.like ? {
        like: null
    } : value == InteractionType.click ? {
        click: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlgorithmSource): {
    hybrid: null;
} | {
    collaborative: null;
} | {
    contentBased: null;
} {
    return value == AlgorithmSource.hybrid ? {
        hybrid: null
    } : value == AlgorithmSource.collaborative ? {
        collaborative: null
    } : value == AlgorithmSource.contentBased ? {
        contentBased: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
